version: '3.1'
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: timetomeet
      MYSQL_USER: deno
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes: 
      - ./db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  deno:
    image: denoland/deno
    container_name: deno
    command: ["run", "--allow-net", "main.ts"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    restart: always
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    

